version: "3"

set: [e, u, pipefail]

includes:
  etc:
    taskfile: etc
    dir: etc
  home:
    taskfile: home
    dir: home
  pkg:
    taskfile: pkg
    dir: pkg
  win:
    taskfile: win
    dir: win
  wsl:
    taskfile: wsl
    dir: wsl

tasks:
  enable:corepack:
    cmds:
      - PATH=/usr/bin sudo corepack enable --install-directory /usr/local/bin
      - PATH=/usr/bin sudo corepack enable --install-directory /usr/local/bin npm
    status:
      - test -L /usr/local/bin/npm
