"$schema" = 'https://starship.rs/config-schema.json'

[time]
disabled = false

[directory]
fish_style_pwd_dir_length = 1
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_status]
format = '([\[$conflicted$ahead_behind\]]($style) )'

[custom.direnv]
format = '[\[direnv\]]($style) '
style = "fg:yellow"
when = 'test -n "$DIRENV_FILE"'

[package]
disabled = true

[container]
disabled = true

#[kubernetes]
#detect_files = ["k8s"]
#disabled = false
