shell = "zsh"

apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.vivid]
inline = 'export LS_COLORS="$(vivid generate one-dark)"'

[plugins.dotfiles]
local = "~/.config/zsh/.zshrc.d"
use = ["*.zsh"]
apply = ["source"]

[plugins.zoxide]
inline = 'zsh-defer -c "$(zoxide init zsh)"'

[plugins.direnv]
inline = 'zsh-defer -c "$(direnv hook zsh)"'

[plugins.asdf]
local = "/opt/asdf-vm"

[plugins.pipx]
inline = 'zsh-defer -c "$(register-python-argcomplete -s bash pipx)"'

[plugins.tabtab]
local = "~/.config/tabtab/zsh"
use = ["pnpm.zsh"]

[plugins.docker-compose]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/docker-compose/_docker-compose"
apply = ["fpath"]

[plugins.helmfile]
inline = 'zsh-defer -c "$(helmfile completion zsh); compdef _helmfile helmfile"'

[plugins.bash-completions]
local = "/usr/share/bash-completion/completions"
use = ["aws", "kubie"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
