shell = "zsh"

apply = ["defer"]

[templates]
defer = """
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.vivid]
inline = 'export LS_COLORS="$(vivid generate one-dark)"'

[plugins.zshrc-foreground]
local = "~/.config/zsh/.zshrc.d"
use = ["*.fg.zsh"]
apply = ["source"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zshrc-background]
local = "~/.config/zsh/.zshrc.d"
use = ["*.bg.zsh"]

[plugins.fzf]
local = "/usr/share/fzf"

[plugins.atuin]
inline = 'zsh-defer -c "$(atuin init zsh --disable-up-arrow)"'

[plugins.bd]
github = "Tarrasch/zsh-bd"

[plugins.zoxide]
inline = 'zsh-defer -c "$(zoxide init zsh)"'

[plugins.direnv]
inline = 'zsh-defer -c "$(direnv hook zsh)"'

[plugins.mise]
inline = 'zsh-defer -c "$(mise activate zsh)"'

[plugins.pipx]
inline = 'zsh-defer -c "$(register-python-argcomplete -s bash pipx)"'

[plugins.pnpm]
inline = 'zsh-defer -c "$(pnpm completion zsh)"'

[plugins.helmfile]
inline = 'zsh-defer -c "$(helmfile completion zsh)"'

[plugins.bash-completions]
local = "/usr/share/bash-completion/completions"
use = ["aws", "hwclock", "kubie", "whois"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
