version: "3"

set: [e, u, pipefail]

tasks:
  export:all:
    deps:
      - export:pacman
      - export:pacman-optdep
      - export:paru
      - export:winget
      - export:chocolatey
      - export:github-cli
      - export:helm
      - export:cargo
      - export:julia
      - export:pipx
      - export:pnpm

  export:pacman:
    - pacman -Qqen | grep -Fxvf pacman.ignore.txt > pacman.txt
    - pacman -Qqdtt > pacman.optdep.txt

  import:pacman:
    vars:
      EXPORT: pacman -Qqen | grep -Fxvf pacman.ignore.txt
    cmds:
      - sudo pacman -S --asdeps --needed --noconfirm - < pacman.optdep.txt
      - |-
        rmpkgs="$(comm -23 <({{.EXPORT}}) pacman.txt)"
        if [ -n "$rmpkgs" ]; then
          sudo pacman -D --asdeps $rmpkgs
        fi
      - sudo pacman -S --needed --noconfirm - < pacman.txt
      - task: clean:pacman
    status:
      - test -z "$(comm -3 <(pacman -Qqdtt) pacman.optdep.txt)"
      - test -z "$(comm -3 <({{.EXPORT}}) pacman.txt)"

  export:paru: pacman -Qqem > paru.txt

  import:paru:
    cmds:
      - |-
        rmpkgs="$(comm -23 <(pacman -Qqem) paru.txt)"
        if [ -n "$rmpkgs" ]; then
          paru -Rns --noconfirm $rmpkgs
        fi
      - paru -S --needed - < paru.txt
      - task: clean:pacman
    status:
      - test -z "$(comm -3 <(pacman -Qqem) paru.txt)"
    interactive: true

  clean:pacman:
    cmds:
      - sudo pacman -Rns --noconfirm $(pacman -Qqdt)
    status:
      - test -z "$(pacman -Qqdt)"

  gc:pacman:
    vars:
      GC: pacman -Rsu $(comm -23 <(pacman -Qqd) <(pacman -Qqdtt))
    cmds:
      - sudo {{.GC}}
    status:
      - test "$({{.GC}} --print)" = " there is nothing to do"
    interactive: true

  export:winget:
    cmds:
      - winget.exe export -o /tmp/winget.json
      - defer: rm /tmp/winget.json
      - >-
        jq '
          .[1] as $ignores
          | .[0]
          | .Sources[0].Packages
            |= reduce $ignores[] as $ignore (
              .;
              map(select(
                .PackageIdentifier
                | startswith($ignore)
                | not
              ))
            )
          | .Sources[0].Packages
            |= sort_by(.PackageIdentifier)
        '
        -s /tmp/winget.json winget.ignore.json
        > winget.json

  export:chocolatey:
    - rm chocolatey.config
    - choco.exe export -o chocolatey.config

  export:github-cli: gh extension list | cut -f 2 > github-cli.txt

  import:github-cli:
    vars:
      EXPORT: gh extension list | cut -f 2
    cmds:
      - comm -23 <({{.EXPORT}}) github-cli.txt | xargs -rL1 gh extension remove
      - comm -13 <({{.EXPORT}}) github-cli.txt | xargs -rL1 gh extension install
    status:
      - test -z "$(comm -3 <({{.EXPORT}}) github-cli.txt)"

  export:helm: helm plugin list | tail +2 | cut -f 1 | tr -d ' ' > helm.txt

  setup:cargo: cargo install cargo-update

  export:cargo:
    - tomlq -r '.v1 | keys | .[] | split(" ") | .[0]' ~/.cargo/.crates.toml > cargo.txt
    - task: sync:cargo-config

  import:cargo:
    vars:
      EXPORT: tomlq -r '.v1 | keys | .[] | split(" ") | .[0]' ~/.cargo/.crates.toml
    cmds:
      - task: sync:cargo-config
      - |-
        rmpkgs="$(comm -23 <({{.EXPORT}}) cargo.txt)"
        if [ -n "$rmpkgs" ]; then
          cargo uninstall $rmpkgs
        fi
      - cargo install-update -i $(cat cargo.txt)
    status:
      - test -z "$(comm -3 <({{.EXPORT}}) cargo.txt)"

  sync:cargo-config:
    vars:
      HOME_FILE: ~/.cargo/.install_config.toml
      REPO_FILE: cargo.config.toml
    cmds:
      - |-
        if [ ! -f {{.HOME_FILE}} ] || [ {{.REPO_FILE}} -nt {{.HOME_FILE}} ]; then
          cp --preserve=timestamps {{.REPO_FILE}} {{.HOME_FILE}}
        else
          cp --preserve=timestamps {{.HOME_FILE}} {{.REPO_FILE}}
        fi
    status:
      - test -f {{.HOME_FILE}}
      - test $(stat -c %Y {{.REPO_FILE}}) -eq $(stat -c %Y {{.HOME_FILE}})

  export:julia: cp ~/.julia/environments/v1.8/Project.toml julia.toml

  export:pipx: pipx list --short | cut -d ' ' -f 1 > pipx.txt

  export:pnpm: pnpm ls -g --depth 0 | tail +6 | cut -d ' ' -f 1 > pnpm.txt
